INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 09:17:33] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 09:17:36] "[37mGET /login HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 09:17:41] "[32mPOST /login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 09:17:41] "[37mGET /login HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 09:17:43] "[37mGET /index HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 09:17:43] "[37mGET /auth/initial-registration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 09:17:49] "[37mPOST /auth/initial-registration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 09:17:57] "[37mGET /admin/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 09:17:58] "[37mGET /admin/student/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 09:18:00] "[37mGET /admin/supervisor/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 09:18:01] "[37mGET /admin/project/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 09:18:02] "[37mGET /admin/student/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 09:18:03] "[37mGET /admin/user/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 09:18:08] "[32mPOST /admin/user/delete/ HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 09:18:08] "[37mGET /admin/user/ HTTP/1.1[0m" 200 -
ERROR:app:Exception on /auth/initial-registration [POST]
Traceback (most recent call last):
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Study\UWA\Year3\S2\CITS3200\project\SDURI-Admin-Platform\app\auth\routes.py", line 151, in initial_registration
    mail.send(msg)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask_mail.py", line 165, in configure_host
    host.login(self.mail.username, self.mail.password)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\smtplib.py", line 734, in login
    raise last_exception
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\smtplib.py", line 723, in login
    (code, resp) = self.auth(
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\smtplib.py", line 646, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (534, b'5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbv\n5.7.14 KffPlDyc8sNOoeEtUU6TuO6n8psV5k6X5-HB67zpHeJDbor4L1O6egBRDRn9XAWJ9MzLn\n5.7.14 0IFHK-Y_-CzRcW63M6nTZxTfMwPtoMa_pfsyZ3FZh9zpz4Sl3e10-g8fja1Scxe3>\n5.7.14 Please log in via your web browser and then try again.\n5.7.14  Learn more at\n5.7.14  https://support.google.com/mail/answer/78754 a4sm895942pgl.51 - gsmtp')
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 09:18:12] "[35m[1mPOST /auth/initial-registration HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 09:18:13] "[37mGET /admin/user/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 09:20:11] "[37mGET /auth/initial-registration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 09:20:13] "[37mPOST /auth/initial-registration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 11:27:33] "[37mGET /admin/student/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 11:27:34] "[37mGET /admin/user/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 11:27:34] "[37mGET /admin/static/bootstrap/bootstrap3/swatch/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 11:27:35] "[37mGET /admin/supervisor/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 11:27:36] "[37mGET /admin/user/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 11:27:36] "[37mGET /admin/project/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 11:27:37] "[37mGET /admin/user/ HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 11:27:41] "[32mPOST /admin/user/delete/ HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 11:27:41] "[37mGET /admin/user/ HTTP/1.1[0m" 200 -
INFO:flask_wtf.csrf:The CSRF token has expired.
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 11:27:43] "[37mPOST /auth/initial-registration HTTP/1.1[0m" 200 -
ERROR:app:Exception on /auth/initial-registration [POST]
Traceback (most recent call last):
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Study\UWA\Year3\S2\CITS3200\project\SDURI-Admin-Platform\app\auth\routes.py", line 151, in initial_registration
    mail.send(msg)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\site-packages\flask_mail.py", line 165, in configure_host
    host.login(self.mail.username, self.mail.password)
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\smtplib.py", line 734, in login
    raise last_exception
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\smtplib.py", line 723, in login
    (code, resp) = self.auth(
  File "c:\users\xiaocheng wang\appdata\local\programs\python\python38-32\lib\smtplib.py", line 646, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (534, b'5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbs\n5.7.14 ykSgxBdAWLpiIJf9D-_iUbTEUWC9wfAcuiPw31soQqgqjRccSOdaHWw-411729UZwqt1h\n5.7.14 jnniT3BfWTcGoJblyBnwqCQGhlbPnnAYME6t8CZmryFSSlbmx5YlVrvBgmQO8boR>\n5.7.14 Please log in via your web browser and then try again.\n5.7.14  Learn more at\n5.7.14  https://support.google.com/mail/answer/78754 v1sm1503214pfi.122 - gsmtp')
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 11:27:48] "[35m[1mPOST /auth/initial-registration HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [06/Oct/2020 11:27:52] "[37mGET /admin/user/ HTTP/1.1[0m" 200 -
