INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [09/Sep/2020 11:25:58] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Sep/2020 11:26:00] "[37mGET /project_list HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Sep/2020 11:26:01] "[37mGET /single_project HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Sep/2020 11:26:07] "[37mGET /login HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Sep/2020 11:26:11] "[32mPOST /login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [09/Sep/2020 11:26:11] "[37mGET /student/Cheng HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Sep/2020 11:26:14] "[37mGET /project_list HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Sep/2020 11:26:15] "[37mGET /single_project HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Sep/2020 11:26:17] "[37mGET /project_list HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Sep/2020 11:26:18] "[37mGET /index HTTP/1.1[0m" 200 -
ERROR:app:Exception on /logout [GET]
Traceback (most recent call last):
  File "C:\Users\Xiaocheng Wang\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Xiaocheng Wang\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Xiaocheng Wang\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Xiaocheng Wang\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Xiaocheng Wang\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Xiaocheng Wang\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Study\UWA\Year3\S2\CITS3200\project\SDURI-Admin-Platform\app\routes.py", line 103, in logout
    logout_user()
NameError: name 'logout_user' is not defined
INFO:werkzeug:127.0.0.1 - - [09/Sep/2020 11:26:19] "[35m[1mGET /logout HTTP/1.1[0m" 500 -
